[executor]
flashloan_enabled = false
program_id = "11111111111111111111111111111111"
alt_address = "11111111111111111111111111111111"

[executor.anti_fingerprint]
cu_jitter_range = 1000
fee_collectors_sol = [
    "11111111111111111111111111111111",
    "11111111111111111111111111111111",
    "11111111111111111111111111111111",
]

[jito]
enabled = true
block_engine_urls = [
    "https://mainnet.block-engine.jito.wtf",
    "https://amsterdam.mainnet.block-engine.jito.wtf",
    "https://frankfurt.mainnet.block-engine.jito.wtf",
    "https://ny.mainnet.block-engine.jito.wtf",
    "https://tokyo.mainnet.block-engine.jito.wtf",
    "https://slc.mainnet.block-engine.jito.wtf",
]
tip_percentage = 60
min_tip_lamports = 1000
min_operator_profit_lamports = 5000

[flashblock]
enabled = true
api_key = ""
cu_price_percentage = 30
endpoints = [
    "https://fra.flashblock.trade",
    "https://ams.flashblock.trade",
    "https://nyc.flashblock.trade",
    "https://tok.flashblock.trade",
]

[astralane]
enabled = true
api_key = ""
cu_price_percentage = 30
endpoints = [
    "https://fr.gateway.astralane.io/iris",
    "https://fr2.gateway.astralane.io/iris",
    "https://ams.gateway.astralane.io/iris",
    "https://ams2.gateway.astralane.io/iris",
    "https://la.gateway.astralane.io/iris",
    "https://ny.gateway.astralane.io/iris",
    "https://jp.gateway.astralane.io/iris",
    "https://sg.gateway.astralane.io/iris",
    "https://lim.gateway.astralane.io/iris",
    "https://lit.gateway.astralane.io/iris",
]
