[general]
keypair_path = "~/.config/solana/id.json"
rpc_url = "http://45.157.234.194:8899"
grpc_endpoint = "http://45.157.234.194:10001"
grpc_token = ""
log_level = "info,arb_engine::scanner=debug,solana_streamer_sdk::pool::streamer=debug"

[engine]
max_hops = 3
warmup_secs = 300
warmup_pool_count = 500000
full_scan_interval_secs = 30
min_reserve_sol = 1.0
max_hop_fee = 0.02
min_profit_sol = 0.0001
max_input_sol = 100.0
ternary_iterations = 10
probe_amount_sol = 0.01
max_profit_ratio = 0.1
# base_mints = ["So11111111111111111111111111111111111111112", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"]

[executor]
flashloan_enabled = true
program_id = "8NwGVcMu96JTJwfUKQNXjYMd87JyGWcPkaENe9NPzLCV"
alt_address = "Eppmrwxw2nY6PbKdG8ANUA3EarHJSoXpfDa2u4euCyWu"
fallback_rpc_url = "https://beta.helius-rpc.com/?api-key=89ed37ec-971c-48e0-99db-921d568354e6"

[executor.anti_fingerprint]
cu_jitter_range = 1000
fee_collectors_sol = [
    "A6m1zY2dM2ue4Aem6q2WSZyS3CX4ap39ApyJSCXhB5Fq",
    "A6m1zY2dM2ue4Aem6q2WSZyS3CX4ap39ApyJSCXhB5Fq",
    "A6m1zY2dM2ue4Aem6q2WSZyS3CX4ap39ApyJSCXhB5Fq",
]

[jito]
enabled = false
block_engine_urls = [
    "https://mainnet.block-engine.jito.wtf",
    "https://amsterdam.mainnet.block-engine.jito.wtf",
    "https://frankfurt.mainnet.block-engine.jito.wtf",
    "https://ny.mainnet.block-engine.jito.wtf",
    "https://tokyo.mainnet.block-engine.jito.wtf",
    "https://slc.mainnet.block-engine.jito.wtf",
]
tip_percentage = 60
min_tip_lamports = 10000
min_operator_profit_lamports = 5000

[flashblock]
enabled = false
api_key = ""
priority_fee_lamports = 100000
endpoints = [
    "https://fra.flashblock.trade",
    "https://ams.flashblock.trade",
    "https://nyc.flashblock.trade",
    "https://tok.flashblock.trade",
]

[astralane]
enabled = true
api_key = "xyz_06iaBUneeAX291ZtQbMoGEMAStUaW9YXyHo2dIrkVSwSZiEspN75RJjTupMN"
priority_fee_lamports = 100000
endpoints = [
    "https://fr.gateway.astralane.io/iris2",
    "https://fr2.gateway.astralane.io/iris2",
    "https://ams.gateway.astralane.io/iris2",
    "https://ams2.gateway.astralane.io/iris2",
    "https://la.gateway.astralane.io/iris2",
    "https://ny.gateway.astralane.io/iris2",
    "https://jp.gateway.astralane.io/iris2",
    "https://sg.gateway.astralane.io/iris2",
    "https://lim.gateway.astralane.io/iris2",
    "https://lit.gateway.astralane.io/iris2",
]
